### ISSUE TITLE
Can we move to a more recent version of Nessus?

### ISSUE THREAD

**Issue by jsf9k** [cisagov/nessus-packer#79]
# 💡 Summary #

I'd like to move the COOL Nessus instance to Graviton (ARM64) hardware.  I have verified that this is possible, but it requires two large changes:
- Base the Nessus AMI on Ubuntu rather than Debian
- Upgrade to a more recent version of Nessus, such as the current latest (10.7.4)

If I build a new AMI, is this something you would be amenable to trying @m1j09830?

## Motivation and context ##

The Graviton instance types are more energy efficient and offer increased performance for less money, so we are interested in moving to them wherever x86-64 hardware is not a requirement.  Unfortunately Nessus does not support ARM64 on Debian, but recent versions do support it on Ubuntu; this is the reason for the two large changes mentioned in the previous section.

**Comment by jsf9k** [comment]
Pinging @m1j09830 for a response.

**Comment by m1j09830** [comment]
Sorry for not seeing this earlier. Yes we have no issue with upgrading to the latest version of Nessus as long as it is still compatible with the COOL. From my understanding previously we weren't able to upgrade because of issues encountered when trying to run in the COOL but this was years ago. If those blockers have since been mitigated and we're able to upgrade without losing functionality then we're good with that. 

The only other caveat I would add to this would be to ensure that the licenses that we currently have would still work for the upgraded version. I don't see why they wouldn't but NOM would best be able to answer that.

**Comment by jsf9k** [comment]
@m1j09830 - Can you take a look at the Nessus instance running in env6 of the staging COOL and let me know if it will work for you?  I don't foresee any issues.

**Comment by m1j09830** [comment]
I attempted to test but I do not have access to that staging environment. I only have access to env7 at this time.

**Comment by jsf9k** [comment]
> I attempted to test but I do not have access to that staging environment. I only have access to env7 at this time.

I fixed the issue (the host was missing in the HBAC rule) and @m1j09830 can now access the environment.

**Comment by jsf9k** [comment]
@m1j09830 tested the new AMI and found that it functioned as expected.
